[supervisord]
logfile=/tmp/supervisord-scheduler.log
logfile_maxbytes=50MB
logfile_backups=10
nodaemon=true
loglevel=info
pidfile=/tmp/supervisord-scheduler.pid

[include]
files = /etc/supervisor/conf.d/scheduler.conf
